// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: meals-db-models.proto

package orders_admin_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shop is
type MealDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        []byte  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *MealDb) Reset() {
	*x = MealDb{}
	mi := &file_meals_db_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealDb) ProtoMessage() {}

func (x *MealDb) ProtoReflect() protoreflect.Message {
	mi := &file_meals_db_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealDb.ProtoReflect.Descriptor instead.
func (*MealDb) Descriptor() ([]byte, []int) {
	return file_meals_db_models_proto_rawDescGZIP(), []int{0}
}

func (x *MealDb) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *MealDb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealDb) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MealDb) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type MealsDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MealsDb []*MealDb `protobuf:"bytes,1,rep,name=MealsDb,proto3" json:"MealsDb,omitempty"`
}

func (x *MealsDb) Reset() {
	*x = MealsDb{}
	mi := &file_meals_db_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsDb) ProtoMessage() {}

func (x *MealsDb) ProtoReflect() protoreflect.Message {
	mi := &file_meals_db_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsDb.ProtoReflect.Descriptor instead.
func (*MealsDb) Descriptor() ([]byte, []int) {
	return file_meals_db_models_proto_rawDescGZIP(), []int{1}
}

func (x *MealsDb) GetMealsDb() []*MealDb {
	if x != nil {
		return x.MealsDb
	}
	return nil
}

var File_meals_db_models_proto protoreflect.FileDescriptor

var file_meals_db_models_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x64, 0x62, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22,
	0x68, 0x0a, 0x06, 0x4d, 0x65, 0x61, 0x6c, 0x44, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x4d, 0x65, 0x61,
	0x6c, 0x73, 0x44, 0x62, 0x12, 0x28, 0x0a, 0x07, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d,
	0x65, 0x61, 0x6c, 0x44, 0x62, 0x52, 0x07, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x42, 0x20,
	0x5a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meals_db_models_proto_rawDescOnce sync.Once
	file_meals_db_models_proto_rawDescData = file_meals_db_models_proto_rawDesc
)

func file_meals_db_models_proto_rawDescGZIP() []byte {
	file_meals_db_models_proto_rawDescOnce.Do(func() {
		file_meals_db_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_meals_db_models_proto_rawDescData)
	})
	return file_meals_db_models_proto_rawDescData
}

var file_meals_db_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meals_db_models_proto_goTypes = []any{
	(*MealDb)(nil),  // 0: models.MealDb
	(*MealsDb)(nil), // 1: models.MealsDb
}
var file_meals_db_models_proto_depIdxs = []int32{
	0, // 0: models.MealsDb.MealsDb:type_name -> models.MealDb
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meals_db_models_proto_init() }
func file_meals_db_models_proto_init() {
	if File_meals_db_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meals_db_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meals_db_models_proto_goTypes,
		DependencyIndexes: file_meals_db_models_proto_depIdxs,
		MessageInfos:      file_meals_db_models_proto_msgTypes,
	}.Build()
	File_meals_db_models_proto = out.File
	file_meals_db_models_proto_rawDesc = nil
	file_meals_db_models_proto_goTypes = nil
	file_meals_db_models_proto_depIdxs = nil
}
