// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: meals-db-service.proto

package orders_admin_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealsDbEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MealsDbEmpty) Reset() {
	*x = MealsDbEmpty{}
	mi := &file_meals_db_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsDbEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsDbEmpty) ProtoMessage() {}

func (x *MealsDbEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_meals_db_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsDbEmpty.ProtoReflect.Descriptor instead.
func (*MealsDbEmpty) Descriptor() ([]byte, []int) {
	return file_meals_db_service_proto_rawDescGZIP(), []int{0}
}

var File_meals_db_service_proto protoreflect.FileDescriptor

var file_meals_db_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x64, 0x62, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x1a, 0x15, 0x6d, 0x65, 0x61, 0x6c, 0x73, 0x2d, 0x64, 0x62, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x79, 0x0a, 0x0e, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x44, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x1a, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x44, 0x62, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meals_db_service_proto_rawDescOnce sync.Once
	file_meals_db_service_proto_rawDescData = file_meals_db_service_proto_rawDesc
)

func file_meals_db_service_proto_rawDescGZIP() []byte {
	file_meals_db_service_proto_rawDescOnce.Do(func() {
		file_meals_db_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_meals_db_service_proto_rawDescData)
	})
	return file_meals_db_service_proto_rawDescData
}

var file_meals_db_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meals_db_service_proto_goTypes = []any{
	(*MealsDbEmpty)(nil), // 0: models.MealsDbEmpty
	(*MealsDb)(nil),      // 1: models.MealsDb
}
var file_meals_db_service_proto_depIdxs = []int32{
	1, // 0: models.MealsDbService.CreateMeals:input_type -> models.MealsDb
	0, // 1: models.MealsDbService.GetMeals:input_type -> models.MealsDbEmpty
	0, // 2: models.MealsDbService.CreateMeals:output_type -> models.MealsDbEmpty
	1, // 3: models.MealsDbService.GetMeals:output_type -> models.MealsDb
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meals_db_service_proto_init() }
func file_meals_db_service_proto_init() {
	if File_meals_db_service_proto != nil {
		return
	}
	file_meals_db_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meals_db_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meals_db_service_proto_goTypes,
		DependencyIndexes: file_meals_db_service_proto_depIdxs,
		MessageInfos:      file_meals_db_service_proto_msgTypes,
	}.Build()
	File_meals_db_service_proto = out.File
	file_meals_db_service_proto_rawDesc = nil
	file_meals_db_service_proto_goTypes = nil
	file_meals_db_service_proto_depIdxs = nil
}
