// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: orders-admin-pkg-service.proto

package orders_admin_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderEmpty) Reset() {
	*x = OrderEmpty{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEmpty) ProtoMessage() {}

func (x *OrderEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEmpty.ProtoReflect.Descriptor instead.
func (*OrderEmpty) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{0}
}

type OrderGetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Getter:
	//
	//	*OrderGetter_Uuid
	//	*OrderGetter_Code
	//	*OrderGetter_Name
	Getter isOrderGetter_Getter `protobuf_oneof:"getter"`
}

func (x *OrderGetter) Reset() {
	*x = OrderGetter{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderGetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderGetter) ProtoMessage() {}

func (x *OrderGetter) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderGetter.ProtoReflect.Descriptor instead.
func (*OrderGetter) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{1}
}

func (m *OrderGetter) GetGetter() isOrderGetter_Getter {
	if m != nil {
		return m.Getter
	}
	return nil
}

func (x *OrderGetter) GetUuid() []byte {
	if x, ok := x.GetGetter().(*OrderGetter_Uuid); ok {
		return x.Uuid
	}
	return nil
}

func (x *OrderGetter) GetCode() string {
	if x, ok := x.GetGetter().(*OrderGetter_Code); ok {
		return x.Code
	}
	return ""
}

func (x *OrderGetter) GetName() string {
	if x, ok := x.GetGetter().(*OrderGetter_Name); ok {
		return x.Name
	}
	return ""
}

type isOrderGetter_Getter interface {
	isOrderGetter_Getter()
}

type OrderGetter_Uuid struct {
	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type OrderGetter_Code struct {
	Code string `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type OrderGetter_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*OrderGetter_Uuid) isOrderGetter_Getter() {}

func (*OrderGetter_Code) isOrderGetter_Getter() {}

func (*OrderGetter_Name) isOrderGetter_Getter() {}

var File_orders_admin_pkg_service_proto protoreflect.FileDescriptor

var file_orders_admin_pkg_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70,
	0x6b, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x1d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x59, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x32, 0xa4, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_orders_admin_pkg_service_proto_rawDescOnce sync.Once
	file_orders_admin_pkg_service_proto_rawDescData = file_orders_admin_pkg_service_proto_rawDesc
)

func file_orders_admin_pkg_service_proto_rawDescGZIP() []byte {
	file_orders_admin_pkg_service_proto_rawDescOnce.Do(func() {
		file_orders_admin_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_admin_pkg_service_proto_rawDescData)
	})
	return file_orders_admin_pkg_service_proto_rawDescData
}

var file_orders_admin_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_admin_pkg_service_proto_goTypes = []any{
	(*OrderEmpty)(nil),  // 0: models.OrderEmpty
	(*OrderGetter)(nil), // 1: models.OrderGetter
	(*Order)(nil),       // 2: models.Order
	(*Orders)(nil),      // 3: models.Orders
}
var file_orders_admin_pkg_service_proto_depIdxs = []int32{
	0, // 0: models.OrderService.GetOrders:input_type -> models.OrderEmpty
	2, // 1: models.OrderService.CreateOrder:input_type -> models.Order
	1, // 2: models.OrderService.OrderByName:input_type -> models.OrderGetter
	3, // 3: models.OrderService.GetOrders:output_type -> models.Orders
	0, // 4: models.OrderService.CreateOrder:output_type -> models.OrderEmpty
	2, // 5: models.OrderService.OrderByName:output_type -> models.Order
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_admin_pkg_service_proto_init() }
func file_orders_admin_pkg_service_proto_init() {
	if File_orders_admin_pkg_service_proto != nil {
		return
	}
	file_orders_admin_pkg_models_proto_init()
	file_orders_admin_pkg_service_proto_msgTypes[1].OneofWrappers = []any{
		(*OrderGetter_Uuid)(nil),
		(*OrderGetter_Code)(nil),
		(*OrderGetter_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_admin_pkg_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_admin_pkg_service_proto_goTypes,
		DependencyIndexes: file_orders_admin_pkg_service_proto_depIdxs,
		MessageInfos:      file_orders_admin_pkg_service_proto_msgTypes,
	}.Build()
	File_orders_admin_pkg_service_proto = out.File
	file_orders_admin_pkg_service_proto_rawDesc = nil
	file_orders_admin_pkg_service_proto_goTypes = nil
	file_orders_admin_pkg_service_proto_depIdxs = nil
}
