// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: orders-admin-pkg-service.proto

package orders_admin_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealsDbEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MealsDbEmpty) Reset() {
	*x = MealsDbEmpty{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealsDbEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealsDbEmpty) ProtoMessage() {}

func (x *MealsDbEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealsDbEmpty.ProtoReflect.Descriptor instead.
func (*MealsDbEmpty) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{0}
}

type OrderAdminEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderAdminEmpty) Reset() {
	*x = OrderAdminEmpty{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAdminEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAdminEmpty) ProtoMessage() {}

func (x *OrderAdminEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAdminEmpty.ProtoReflect.Descriptor instead.
func (*OrderAdminEmpty) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{1}
}

type OrderDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Day  string `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *OrderDeleteReq) Reset() {
	*x = OrderDeleteReq{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteReq) ProtoMessage() {}

func (x *OrderDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteReq.ProtoReflect.Descriptor instead.
func (*OrderDeleteReq) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDeleteReq) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *OrderDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderDeleteReq) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type OrderAdminGetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Getter:
	//
	//	*OrderAdminGetter_Uuid
	//	*OrderAdminGetter_Code
	//	*OrderAdminGetter_Name
	Getter isOrderAdminGetter_Getter `protobuf_oneof:"getter"`
}

func (x *OrderAdminGetter) Reset() {
	*x = OrderAdminGetter{}
	mi := &file_orders_admin_pkg_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAdminGetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAdminGetter) ProtoMessage() {}

func (x *OrderAdminGetter) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAdminGetter.ProtoReflect.Descriptor instead.
func (*OrderAdminGetter) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_service_proto_rawDescGZIP(), []int{3}
}

func (m *OrderAdminGetter) GetGetter() isOrderAdminGetter_Getter {
	if m != nil {
		return m.Getter
	}
	return nil
}

func (x *OrderAdminGetter) GetUuid() []byte {
	if x, ok := x.GetGetter().(*OrderAdminGetter_Uuid); ok {
		return x.Uuid
	}
	return nil
}

func (x *OrderAdminGetter) GetCode() string {
	if x, ok := x.GetGetter().(*OrderAdminGetter_Code); ok {
		return x.Code
	}
	return ""
}

func (x *OrderAdminGetter) GetName() string {
	if x, ok := x.GetGetter().(*OrderAdminGetter_Name); ok {
		return x.Name
	}
	return ""
}

type isOrderAdminGetter_Getter interface {
	isOrderAdminGetter_Getter()
}

type OrderAdminGetter_Uuid struct {
	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3,oneof"`
}

type OrderAdminGetter_Code struct {
	Code string `protobuf:"bytes,2,opt,name=code,proto3,oneof"`
}

type OrderAdminGetter_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*OrderAdminGetter_Uuid) isOrderAdminGetter_Getter() {}

func (*OrderAdminGetter_Code) isOrderAdminGetter_Getter() {}

func (*OrderAdminGetter_Name) isOrderAdminGetter_Getter() {}

var File_orders_admin_pkg_service_proto protoreflect.FileDescriptor

var file_orders_admin_pkg_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70,
	0x6b, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x1d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4a, 0x0a, 0x0e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x5e, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x67, 0x65, 0x74, 0x74, 0x65, 0x72, 0x32, 0xf2, 0x02, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x17, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74, 0x74, 0x65, 0x72, 0x1a, 0x12,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x3e, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x34, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x61, 0x6c,
	0x73, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73,
	0x44, 0x62, 0x1a, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c,
	0x73, 0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65,
	0x61, 0x6c, 0x73, 0x44, 0x62, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x73, 0x44, 0x62, 0x42, 0x20, 0x5a, 0x1e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orders_admin_pkg_service_proto_rawDescOnce sync.Once
	file_orders_admin_pkg_service_proto_rawDescData = file_orders_admin_pkg_service_proto_rawDesc
)

func file_orders_admin_pkg_service_proto_rawDescGZIP() []byte {
	file_orders_admin_pkg_service_proto_rawDescOnce.Do(func() {
		file_orders_admin_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_admin_pkg_service_proto_rawDescData)
	})
	return file_orders_admin_pkg_service_proto_rawDescData
}

var file_orders_admin_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orders_admin_pkg_service_proto_goTypes = []any{
	(*MealsDbEmpty)(nil),     // 0: models.MealsDbEmpty
	(*OrderAdminEmpty)(nil),  // 1: models.OrderAdminEmpty
	(*OrderDeleteReq)(nil),   // 2: models.OrderDeleteReq
	(*OrderAdminGetter)(nil), // 3: models.OrderAdminGetter
	(*OrdersAdmin)(nil),      // 4: models.OrdersAdmin
	(*MealsDb)(nil),          // 5: models.MealsDb
	(*OrderAdmin)(nil),       // 6: models.OrderAdmin
}
var file_orders_admin_pkg_service_proto_depIdxs = []int32{
	1, // 0: models.OrderAdminService.GetOrders:input_type -> models.OrderAdminEmpty
	4, // 1: models.OrderAdminService.CreateOrders:input_type -> models.OrdersAdmin
	3, // 2: models.OrderAdminService.OrderByName:input_type -> models.OrderAdminGetter
	2, // 3: models.OrderAdminService.DeleteOrder:input_type -> models.OrderDeleteReq
	5, // 4: models.OrderAdminService.CreateMeals:input_type -> models.MealsDb
	0, // 5: models.OrderAdminService.GetMeals:input_type -> models.MealsDbEmpty
	4, // 6: models.OrderAdminService.GetOrders:output_type -> models.OrdersAdmin
	1, // 7: models.OrderAdminService.CreateOrders:output_type -> models.OrderAdminEmpty
	6, // 8: models.OrderAdminService.OrderByName:output_type -> models.OrderAdmin
	1, // 9: models.OrderAdminService.DeleteOrder:output_type -> models.OrderAdminEmpty
	0, // 10: models.OrderAdminService.CreateMeals:output_type -> models.MealsDbEmpty
	5, // 11: models.OrderAdminService.GetMeals:output_type -> models.MealsDb
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_admin_pkg_service_proto_init() }
func file_orders_admin_pkg_service_proto_init() {
	if File_orders_admin_pkg_service_proto != nil {
		return
	}
	file_orders_admin_pkg_models_proto_init()
	file_orders_admin_pkg_service_proto_msgTypes[3].OneofWrappers = []any{
		(*OrderAdminGetter_Uuid)(nil),
		(*OrderAdminGetter_Code)(nil),
		(*OrderAdminGetter_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_admin_pkg_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_admin_pkg_service_proto_goTypes,
		DependencyIndexes: file_orders_admin_pkg_service_proto_depIdxs,
		MessageInfos:      file_orders_admin_pkg_service_proto_msgTypes,
	}.Build()
	File_orders_admin_pkg_service_proto = out.File
	file_orders_admin_pkg_service_proto_rawDesc = nil
	file_orders_admin_pkg_service_proto_goTypes = nil
	file_orders_admin_pkg_service_proto_depIdxs = nil
}
