// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.0
// source: orders-admin-pkg-models.proto

package orders_admin_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shop is
type OrderAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     []byte  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MealType string  `protobuf:"bytes,3,opt,name=mealType,proto3" json:"mealType,omitempty"`
	Price    float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity int32   `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Day      string  `protobuf:"bytes,6,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *OrderAdmin) Reset() {
	*x = OrderAdmin{}
	mi := &file_orders_admin_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAdmin) ProtoMessage() {}

func (x *OrderAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAdmin.ProtoReflect.Descriptor instead.
func (*OrderAdmin) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *OrderAdmin) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *OrderAdmin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderAdmin) GetMealType() string {
	if x != nil {
		return x.MealType
	}
	return ""
}

func (x *OrderAdmin) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderAdmin) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderAdmin) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type OrdersAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdersAdmin []*OrderAdmin `protobuf:"bytes,1,rep,name=OrdersAdmin,proto3" json:"OrdersAdmin,omitempty"`
}

func (x *OrdersAdmin) Reset() {
	*x = OrdersAdmin{}
	mi := &file_orders_admin_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersAdmin) ProtoMessage() {}

func (x *OrdersAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_orders_admin_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersAdmin.ProtoReflect.Descriptor instead.
func (*OrdersAdmin) Descriptor() ([]byte, []int) {
	return file_orders_admin_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *OrdersAdmin) GetOrdersAdmin() []*OrderAdmin {
	if x != nil {
		return x.OrdersAdmin
	}
	return nil
}

var File_orders_admin_pkg_models_proto protoreflect.FileDescriptor

var file_orders_admin_pkg_models_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70,
	0x6b, 0x67, 0x2d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x43,
	0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x34, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2d, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orders_admin_pkg_models_proto_rawDescOnce sync.Once
	file_orders_admin_pkg_models_proto_rawDescData = file_orders_admin_pkg_models_proto_rawDesc
)

func file_orders_admin_pkg_models_proto_rawDescGZIP() []byte {
	file_orders_admin_pkg_models_proto_rawDescOnce.Do(func() {
		file_orders_admin_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_admin_pkg_models_proto_rawDescData)
	})
	return file_orders_admin_pkg_models_proto_rawDescData
}

var file_orders_admin_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_admin_pkg_models_proto_goTypes = []any{
	(*OrderAdmin)(nil),  // 0: models.OrderAdmin
	(*OrdersAdmin)(nil), // 1: models.OrdersAdmin
}
var file_orders_admin_pkg_models_proto_depIdxs = []int32{
	0, // 0: models.OrdersAdmin.OrdersAdmin:type_name -> models.OrderAdmin
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orders_admin_pkg_models_proto_init() }
func file_orders_admin_pkg_models_proto_init() {
	if File_orders_admin_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_admin_pkg_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orders_admin_pkg_models_proto_goTypes,
		DependencyIndexes: file_orders_admin_pkg_models_proto_depIdxs,
		MessageInfos:      file_orders_admin_pkg_models_proto_msgTypes,
	}.Build()
	File_orders_admin_pkg_models_proto = out.File
	file_orders_admin_pkg_models_proto_rawDesc = nil
	file_orders_admin_pkg_models_proto_goTypes = nil
	file_orders_admin_pkg_models_proto_depIdxs = nil
}
